# Generated by Django 2.1.7 on 2019-03-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='Agility_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='char',
            name='FatePoints_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='char',
            name='Fellowship_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='char',
            name='Intelligence_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='char',
            name='Melee_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='char',
            name='Perception_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='char',
            name='Range_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='char',
            name='Strength_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='char',
            name='Toughness_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='char',
            name='WillPower_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
